CREATE USER persal_user WITH PASSWORD '990302';
CREATE DATABASE persal_fresh OWNER persal_user;
GRANT ALL PRIVILEGES ON DATABASE persal_fresh TO persal_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO persal_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO persal_user;
